openapi: 3.0.3
info:
  title: Football Competition 
  version: '1.0.0'
servers:
  - url: https://localhost.football-competition.com

paths:
  /competitions:
    get:
      summary: Get a list of competitions
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
          description: The page number 
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
          description: The number of items 
      responses:
        200:
          description: The list of competitions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
    post:
      summary: Create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Competition'
      responses:
        201:
          description: Competition created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Competition'

/teams:
    get:
      summary: Get a list of teams
      parameters:
        - in: query
          name: teamName
          schema:
            type: string
          required: false
          description: Filter teams by name
        - in: query
          name: page
          schema:
            type: integer
          required: true
          description: The page number 
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
          description: The number of items for each page
      responses:
        200:
          description: The list of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    post:
      summary: Create  new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        201:
          description: Team created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'

  